# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for boxes at https://vagrantcloud.com/search.
  # config.vm.box = "jasonc/centos7"
  # config.vm.box = "manhattanprep/tomcat-java"
  # config.vm.box = "naphatkrit/rabbitmq"
  # config.vm.box = "pirofex/tomcat-memcached"
  # config.vm.box = "obihann/nginx"

  ### DB Virtual Machine  ####
  config.vm.define "mysql01" do |mysql01|
    mysql01.vm.box = "eurolinux-vagrant/centos-stream-9"
    mysql01.vm.hostname = "mysql01"
    mysql01.vm.network "private_network", ip: "10.9.8.55"
    mysql01.vm.provider "virtualbox" do |vb|
      vb.memory = "600"
    end
  end

  ### Memcache Virtual Machine  ####
  config.vm.define "memcache01" do |memcache01|
    memcache01.vm.box = "eurolinux-vagrant/centos-stream-9"
    memcache01.vm.hostname = "memcache01"
    memcache01.vm.network "private_network", ip: "10.9.8.54"
    memcache01.vm.provider "virtualbox" do |vb|
      vb.memory = "600"
    end
  end

  ### RabbitMQ Virtual Machine  ####
  config.vm.define "rabbitmq01" do |rabbitmq01|
    rabbitmq01.vm.box = "eurolinux-vagrant/centos-stream-9"
    rabbitmq01.vm.hostname = "rabbitmq01"
    rabbitmq01.vm.network "private_network", ip: "10.9.8.53"
    rabbitmq01.vm.provider "virtualbox" do |vb|
      vb.memory = "600"
    end
  end

  ### Tomcat Virtual Machine  ####
  config.vm.define "app01" do |app01|
    app01.vm.box = "eurolinux-vagrant/centos-stream-9"
    app01.vm.hostname = "app01"
    app01.vm.network "private_network", ip: "10.9.8.52"
    app01.vm.provider "virtualbox" do |vb|
      vb.memory = "600"
    end
  end


  ### Nginx Virtual Machine  ####
  config.vm.define "web01" do |web01|
    web01.vm.box = "obihann/nginx"
    web01.vm.hostname = "web01"
    web01.vm.network "private_network", ip: "10.9.8.51"
    web01.vm.provider "virtualbox" do |vb|
      vb.memory = "600"
    end
  end


  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Disable the default share of the current code directory. Doing this
  # provides improved isolation between the vagrant box and your host
  # by making sure your Vagrantfile isn't accessable to the vagrant box.
  # If you use this you may want to enable additional shared subfolders as
  # shown above.
  # config.vm.synced_folder ".", "/vagrant", disabled: true

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end
